import type { Metadata } from 'next'
// import './globals.css'
import '@stewardly/ui/dist/index.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <div className="bg-gray-100 dark:bg-slate-900"></div>
        {children}
      </body>
    </html>
  )
}
